export const searchList = [
    'Chairs',
    'Sofas',
    'Tables',
    'Lamps',
    'Bookcase',
    'Nightstand',
    'Wardrobe',
    'Couch',
    'Coffee Table',
    'Bureau',
    'Bench',
    'Desk',
    'Ottoman',
    'Stool',
    'Cabinetry',
    'Recliner',
    'Armchair',
    'Cupboard',
    'Bar Stool',
    'Filing cabinet',
    'Kitchen cabinet',
    'Bed'
]